const persianWords = {
    easy: [
        { word: 'سگ', english: 'dog' },
        { word: 'گربه', english: 'cat' },
        { word: 'خانه', english: 'house' },
        { word: 'ماشین', english: 'car' },
        { word: 'کتاب', english: 'book' },
        { word: 'درخت', english: 'tree' },
        { word: 'خورشید', english: 'sun' },
        { word: 'ماه', english: 'moon' },
        { word: 'ستاره', english: 'star' },
        { word: 'آب', english: 'water' },
        { word: 'نان', english: 'bread' },
        { word: 'چای', english: 'tea' },
        { word: 'قهوه', english: 'coffee' },
        { word: 'سیب', english: 'apple' },
        { word: 'پرتقال', english: 'orange' },
        { word: 'اسب', english: 'horse' },
        { word: 'گاو', english: 'cow' },
        { word: 'پرنده', english: 'bird' },
        { word: 'ماهی', english: 'fish' }
    ],
    
    medium: [
        { word: 'اسکله', english: 'pier' },
        { word: 'کارآفرین', english: 'entrepreneur' },
        { word: 'شناسنامه', english: 'birth certificate' },
        { word: 'سیمرغ', english: 'simorgh' },
        { word: 'داروخانه', english: 'pharmacy' },
        { word: 'دومینو', english: 'domino' },
        { word: 'منگل', english: 'brazier' },
        { word: 'سمج', english: 'stubborn' },
        { word: 'دولت', english: 'government' },
        { word: 'آبگوشت', english: 'abgoosht' },
        { word: 'کارنامه', english: 'report card' },
        { word: 'اختاپوس', english: 'octopus' },
        { word: 'حنابندان', english: 'henna ceremony' },
        { word: 'دورنما', english: 'panorama' },
        { word: 'خرناس', english: 'snout' },
        { word: 'تابلو', english: 'painting' },
        { word: 'دنده', english: 'gear' },
        { word: 'اتو', english: 'iron' },
        { word: 'روزنامه', english: 'newspaper' },
        { word: 'قاتل', english: 'killer' },
        { word: 'مترسک', english: 'scarecrow' },
        { word: 'گذرنامه', english: 'passport' },
        { word: 'ترامپ', english: 'Trump' },
        { word: 'شیطان', english: 'devil' },
        { word: 'رادیولوژی', english: 'radiology' },
        { word: 'محله', english: 'neighborhood' },
        { word: 'مجله', english: 'magazine' },
        { word: 'شکایت', english: 'complaint' },
        { word: 'اسب تروا', english: 'Trojan horse' },
        { word: 'نیمکت ذخیره', english: 'bench' },
        { word: 'کلاه قرمزی', english: 'red hat' },
        { word: 'ژ گونه', english: 'cheekbone' },
        { word: 'دستمال کاغذی', english: 'tissue' },
        { word: 'قفسه کتاب', english: 'bookshelf' },
        { word: 'ساعت مچی', english: 'wristwatch' },
        { word: 'مرغ عشق', english: 'lovebird' },
        { word: 'پرده کرکره', english: 'blinds' },
        { word: 'ساعت دیواری', english: 'wall clock' },
        { word: 'دیوار چین', english: 'Great Wall' },
        { word: 'پیراهن مبل', english: 'sofa cover' },
        { word: 'ایستگاه صلواتی', english: 'prayer station' },
        { word: 'چهل چراغ', english: 'forty lamps' },
        { word: 'کوکو سبزی', english: 'herb frittata' },
        { word: 'کباب تابه‌ای', english: 'pan kebab' },
        { word: 'اصحاب کهف', english: 'people of cave' },
        { word: 'کبوتر صلح', english: 'peace dove' },
        { word: 'پلنگ صورتی', english: 'pink panther' }
    ],
    
    hard: [
        { word: 'اهرام ثلاثه مصر', english: 'pyramids of Egypt' },
        { word: 'قانون اول نیوتن', english: 'Newton first law' },
        { word: 'جنگل اسرار آمیز', english: 'mysterious jungle' },
        { word: 'اینترنت نسل سوم', english: '3G internet' },
        { word: 'مرخصی بدون حقوق', english: 'unpaid leave' },
        { word: 'سازمان ملل متحد', english: 'United Nations' },
        { word: 'مدیر منابع انسانی', english: 'HR manager' },
        { word: 'کوچه علی چپ', english: 'Ali Chap alley' },
        { word: 'واشر سر سیلندر', english: 'cylinder head gasket' },
        { word: 'مهمان ناخوانده', english: 'uninvited guest' },
        { word: 'محلول در آب', english: 'water soluble' },
        { word: 'مدار صفر درجه', english: 'zero degree circuit' },
        { word: 'خواننده زیر زمینی', english: 'underground singer' },
        { word: 'شاگرد مغازه کله‌پزی', english: 'sheep head shop apprentice' },
        { word: 'دنباله لباس عروس', english: 'wedding dress train' },
        { word: 'خط عابر پیاده', english: 'crosswalk' },
        { word: 'بابا طاهر عریان', english: 'Baba Taher' },
        { word: 'پشمک حاج عبدالله', english: 'cotton candy' },
        { word: 'کتاب دست دوم', english: 'second-hand book' },
        { word: 'گل گاو زبان', english: 'borage flower' },
        { word: 'قزن قفلی لباس', english: 'zipper' },
        { word: 'محل وقوع جرم', english: 'crime scene' },
        { word: 'سه راه سلفچگان', english: 'Solfchegan junction' },
        { word: 'ایران سرای امید', english: 'Iran Land of Hope' },
        { word: 'پاپیروس', english: 'papyrus' },
        { word: 'اورولوژیست', english: 'urologist' },
        { word: 'یاتاقان', english: 'yatagan' },
        { word: 'یبوست', english: 'constipation' },
        { word: 'تشریفات', english: 'protocol' },
        { word: 'وقاحت', english: 'impudence' },
        { word: 'پهباد', english: 'drone' },
        { word: 'کروموزوم', english: 'chromosome' },
        { word: 'فراماسونری', english: 'freemasonry' },
        { word: 'مونالیزا', english: 'Mona Lisa' },
        { word: 'اسهال', english: 'diarrhea' },
        { word: 'فرابنفش', english: 'ultraviolet' },
        { word: 'هولوکاست', english: 'holocaust' },
        { word: 'افشاگری', english: 'disclosure' },
        { word: 'گستاخ', english: 'insolent' },
        { word: 'لاتاری', english: 'lottery' },
        { word: 'پانتومیم', english: 'pantomime' },
        { word: 'ابتکار', english: 'initiative' },
        { word: 'ابوالهول', english: 'sphinx' },
        { word: 'فروگذار', english: 'humble' },
        { word: 'ققنوس', english: 'phoenix' },
        { word: 'بولینگ', english: 'bowling' },
        { word: 'کنکور', english: 'entrance exam' },
        { word: 'پرسپکتیو', english: 'perspective' },
        { word: 'کلاچ', english: 'clutch' },
        { word: 'مقتول', english: 'murdered' },
        { word: 'اوباما', english: 'Obama' },
        { word: 'مخلوط', english: 'mixed' },
        { word: 'تزریقاتی', english: 'injectable' },
        { word: 'چرنوبیل', english: 'Chernobyl' },
        { word: 'کروکودیل', english: 'crocodile' },
        { word: 'فرشته', english: 'angel' },
        { word: 'اسکول', english: 'stupid' },
        { word: 'دیزی', english: 'dizi' }
    ],
    
    phrases: [
        { word: 'شتر سواری دولا دولا نمی‌شود', english: 'proverb' },
        { word: 'هر چه نخ کردم پنبه شد', english: 'proverb' },
        { word: 'سر پیازی یا ته پیاز؟', english: 'phrase' },
        { word: 'قطره قطره جمع گردد وانگهی دریا شود', english: 'proverb' },
        { word: 'از دور دل را می‌برد، از جلو زهره را', english: 'proverb' },
        { word: 'بار کج به منزل نمی‌رسد', english: 'proverb' },
        { word: 'آستین نو، پلو بخور', english: 'proverb' },
        { word: 'اسب پیش‌کشی‌ را، دندان‌هایش را نمی‌شمرند', english: 'proverb' },
        { word: 'دیر آمده زود میخواهد برود', english: 'proverb' },
        { word: 'آش نخورده و دهن سوخته', english: 'proverb' },
        { word: 'هر چی سنگه مال پای لنگه', english: 'proverb' },
        { word: 'شتر دیدی ندیدی', english: 'phrase' },
        { word: 'از آب گل آلود ماهی می‌گیرد', english: 'proverb' },
        { word: 'از آب کره می‌گیرد', english: 'proverb' },
        { word: 'هم فاله و هم تماشا', english: 'proverb' },
        { word: 'دیوار موش داره، موش هم گوش داره', english: 'proverb' },
        { word: 'برو کشک‌تو بساب', english: 'phrase' },
        { word: 'یکی به نعل، یکی به میخ', english: 'proverb' },
        { word: 'ترشی نخوری یه چیزی میشی', english: 'phrase' }
    ]
};

const englishWords = {
    easy: [
        { word: 'dog', persian: 'سگ' },
        { word: 'cat', persian: 'گربه' },
        { word: 'house', persian: 'خانه' },
        { word: 'car', persian: 'ماشین' },
        { word: 'book', persian: 'کتاب' },
        { word: 'tree', persian: 'درخت' },
        { word: 'sun', persian: 'خورشید' },
        { word: 'moon', persian: 'ماه' },
        { word: 'star', persian: 'ستاره' },
        { word: 'water', persian: 'آب' },
        { word: 'bread', persian: 'نان' },
        { word: 'tea', persian: 'چای' },
        { word: 'coffee', persian: 'قهوه' },
        { word: 'apple', persian: 'سیب' },
        { word: 'horse', persian: 'اسب' },
        { word: 'bird', persian: 'پرنده' }
    ],
    medium: [
        { word: 'lighthouse', persian: 'فانوس دریایی' },
        { word: 'passport', persian: 'گذرنامه' },
        { word: 'accordion', persian: 'آکاردئون' },
        { word: 'gallery', persian: 'نگارخانه' },
        { word: 'newspaper', persian: 'روزنامه' },
        { word: 'domino', persian: 'دومینو' },
        { word: 'scarecrow', persian: 'مترسک' },
        { word: 'fireplace', persian: 'شومینه' },
        { word: 'carousel', persian: 'چرخ و فلک' },
        { word: 'treasure map', persian: 'نقشه گنج' },
        { word: 'fortune teller', persian: 'فالگیر' },
        { word: 'roller coaster', persian: 'ترن هوایی' },
        { word: 'campfire', persian: 'آتش کمپ' },
        { word: 'chalkboard', persian: 'تخته سیاه' },
        { word: 'microscope', persian: 'میکروسکوپ' }
    ],
    hard: [
        { word: 'time capsule', persian: 'کپسول زمان' },
        { word: 'pyramid', persian: 'هرم' },
        { word: 'spaceship', persian: 'سفینه فضایی' },
        { word: 'circuit board', persian: 'برد مدار چاپی' },
        { word: 'meteor shower', persian: 'بارش شهابی' },
        { word: 'quantum physics', persian: 'فیزیک کوانتوم' },
        { word: 'eiffel tower', persian: 'برج ایفل' },
        { word: 'unwritten rules', persian: 'قوانین نانوشته' },
        { word: 'optical illusion', persian: 'خطای دید' },
        { word: 'philosopher', persian: 'فیلسوف' },
        { word: 'civilization', persian: 'تمدن' },
        { word: 'hologram', persian: 'هولوگرام' },
        { word: 'cliffhanger', persian: 'پایان معلق' },
        { word: 'marathon runner', persian: 'دونده ماراتن' },
        { word: 'gravity', persian: 'جاذبه' }
    ],
    phrases: [
        { word: 'break the ice', persian: 'یخ شکستن' },
        { word: 'piece of cake', persian: 'خیلی آسان' },
        { word: 'under the weather', persian: 'کسالت داشتن' },
        { word: 'once in a blue moon', persian: 'گاه به گاه' },
        { word: 'spill the beans', persian: 'لو دادن راز' },
        { word: 'hit the books', persian: 'درس خواندن' },
        { word: 'on the same page', persian: 'هم عقیده بودن' },
        { word: 'silver lining', persian: 'نکته مثبت' },
        { word: 'burning the midnight oil', persian: 'تا دیر وقت بیدار ماندن' },
        { word: 'elephant in the room', persian: 'مشکل واضح ولی نادیده' },
        { word: 'call it a day', persian: 'تمام کردن کار' },
        { word: 'hit the nail on the head', persian: 'درست گفتن' },
        { word: 'let the cat out of the bag', persian: 'راز را فاش کردن' },
        { word: 'beat around the bush', persian: 'دور حرف زدن' },
        { word: 'pulling your leg', persian: 'سر به سر گذاشتن' }
    ]
};

if (typeof module !== 'undefined') {
    module.exports = { persianWords, englishWords };
}
